package com.mj.tic.tac.toe.javafx.java.util;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.With;

/**
 * Represents an immutable pair of (x, y) coordinates on a 2D grid used to
 * identify cell positions in the Tic-Tac-Toe board.
 * <p>
 * Instances can be created via {@link #Coordinates(int, int)} and are safe to
 * use as map keys or set elements.  Use the {@code withX} / {@code withY}
 * methods (generated by Lombok's {@code @With}) to produce a new instance
 * differing in only one coordinate.
 *
 * @author Montaser Sbaih
 * @version 1.0
 * @email montaser.jjs@gmail.com
 * @phone +962-786258874
 * @since 20-01-2023
 */

@Data
@With
@AllArgsConstructor
public final class Coordinates {

    private final int x;

    private final int y;
}
