# Button
control.button.default=BUTTON
control.button.ok=OK
control.button.no=NO
control.button.yes=YES
control.button.cancel=CANCEL
control.button.confirm=CONFIRM
control.button.play=PLAY
control.button.reset=RESET
# Label
control.label.default=Label
control.label.title.default=Title
control.label.title.app=Tic Tac Toe
control.label.draw=Draw
control.label.wins.x=X wins
control.label.wins.o=O wins
control.label.alert=Alert