# Button
control.button.default=BUTTON
control.button.ok=OK
control.button.no=NO
control.button.yes=YES
control.button.cancel=CANCEL
control.button.confirm=CONFIRM
control.button.play=PLAY
control.button.reset=RESET
control.button.difficulty.easy=EASY
control.button.difficulty.medium=MEDIUM
control.button.difficulty.hard=HARD
# Label
control.label.default=Label
control.label.title.default=Title
control.label.title.app=Tic Tac Toe
control.label.title.difficulty=Select Difficulty
control.label.difficulty.level=Difficulty :
control.label.difficulty.default=Not specified
control.label.difficulty.easy=Easy
control.label.difficulty.medium=Medium
control.label.difficulty.hard=Hard
control.label.draw=Draw
control.label.wins.human=Your wins
control.label.wins.computer=Computer's wins
control.label.alert=Alert